name: Tidelift Alignment
on:
  push:
    paths:
      - '.github/workflows/tidelift-alignment.yml'
      - 'package.json'

jobs:
  build:
    name: Run Tidelift to ensure approved open source packages are in use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Setup node
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3.1.1
        with:
          node-version: 16
      - name: Alignment
        uses: tidelift/alignment-action@8d7700fe795fc01179c1f9fa05b72a089873027d # main
        env:
          TIDELIFT_API_KEY: ${{ secrets.TIDELIFT_API_KEY }}
          TIDELIFT_ORGANIZATION: ${{ secrets.TIDELIFT_ORGANIZATION }}
          TIDELIFT_PROJECT: ${{ secrets.TIDELIFT_PROJECT }}